feature_extractor:
  encodec_model: encodec_24khz
  bandwidths: [6.6, 6.6, 6.6, 6.6]
  train_codebooks: true
  num_quantizers: 1  
  dowmsamples: [8, 5, 4, 2]
  vq_bins: 4096
  vq_kmeans: 200

backbone:
  input_channels: 512
  dim: 768
  intermediate_dim: 2304
  num_layers: 12
  adanorm_num_embeddings: 4  

head:
  dim: 768
  n_fft: 1280 
  hop_length: 320  
  padding: same